DnDe5.Web/Models/Encounters/EncounterModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DnDe5.Web.Models.Encounters
{
    public class EncounterModel
    {
        public EncounterModel()
        {

        }

        public Guid Id { get; set; }
        public string EncounterName { get; set; }
        public List<Monster> Monsters { get; set; }
    }
}

DnDe5.Web/Models/Encounters/Monster.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web.Mvc.Html;
using System.Web.UI.WebControls;

namespace DnDe5.Web.Models.Encounters
{
    public class Monster
    {
        public string Name { get; set; }

        public int Speed { get; set; }

        public int AC { get; set; }

        public int STR { get; set; }

        public int DEX { get; set; }

        public int CON { get; set; }

        public int INT { get; set; }

        public int WIS { get; set; }

        public int CHA { get; set; }

        public string Alignment { get; set; }

        public int XP { get; set; }

        public string Traits { get; set; }
        public string Actions { get; set; }
        public int HP { get; set; }
        public string Loot { get; set; }
        public string Sense_Immunities { get; set; }
        public string Notes { get; set; }
    }
}

DnDe5.Web/Controllers/EncountersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

using DnDe5.Web.Helpers;
using DnDe5.Web.Models.Encounters;

namespace DnDe5.Web.Controllers
{
    public class EncountersController : Controller
    {
        public ActionResult Index()
        {
            return View(SessionStateSink.SessionEncounters);
        }

        [HttpGet]
        public ActionResult EncounterCreate()
        {
            if (SessionStateSink.SessionEncounter == null)
            { 
                SessionStateSink.SessionEncounter = new EncounterModel();
            }
            return View(SessionStateSink.SessionEncounter);
        }

        [HttpGet]
        public ActionResult EncounterEdit(Guid id)
        {
            SessionStateSink.SessionEncounter = SessionStateSink.SessionEncounters[id];
            
            return View("EncounterCreate", SessionStateSink.SessionEncounter);
        }

        [HttpPost]
        public ActionResult EncounterCreate(EncounterModel model)
        {
            if (SessionStateSink.SessionEncounters == null)
            {
                SessionStateSink.SessionEncounters = new Dictionary<Guid, EncounterModel>();
            }
            model.Id = Guid.NewGuid();
            model.Monsters = new List<Monster>();
            
            SessionStateSink.SessionEncounters.Add(model.Id, model);

            return View(SessionStateSink.SessionEncounter);
        }

        [HttpPost]
        public ActionResult MonsterCreate(Monster monster, Guid encounterId)
        {
            SessionStateSink.SessionEncounters[encounterId].Monsters.Add(monster);
            return RedirectToAction("EncounterCreate", new RouteValueDictionary(new Dictionary<string, object> { { "id", encounterId }}));
        }
    }
}

DnDe5.Web/Views/Encounters/EncounterCreate.cshtml
@using DnDe5.Web.Models.Encounters
@model DnDe5.Web.Models.Encounters.EncounterModel


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Encounter</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EncounterName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EncounterName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EncounterName, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.HiddenFor(model => model.Id)
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@if (Model.Monsters != null)
{
    @Html.Partial("MonsterCreate", new Monster())
}


<section>
    <h1>RESULTS</h1>
    @(Newtonsoft.Json.JsonConvert.SerializeObject(Model))
</section>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DnDe5.Web/Views/Encounters/Index.cshtml
@model IEnumerable<DnDe5.Web.Models.Encounters.EncounterModel>

@{
    ViewBag.Title = "View";
}

<h2>View</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EncounterName)
        </th>
        <th></th>
    </tr>
    @if (Model == null)
    {
        <tr><td colspan="2">No Results</td></tr>
    }
    else
    {
        foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.EncounterName)
                </td>
                <td>
                    @Html.ActionLink("Edit", "EncounterEdit", new { id=item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id=item.Id })
                </td>
            </tr>
        }
    }
</table>

DnDe5.Web/Views/Encounters/MonsterCreate.cshtml
@model DnDe5.Web.Models.Encounters.Monster

@{
    ViewBag.Title = "View1";
}

<h2>View1</h2>

@using (Html.BeginForm("MonsterCreate", "Encounters")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Monster</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Speed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Speed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Speed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.STR, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.STR, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.STR, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DEX, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DEX, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DEX, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CON, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CON, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CON, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.INT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.INT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.INT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WIS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WIS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WIS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CHA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CHA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CHA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Alignment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Alignment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Alignment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.XP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.XP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.XP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Traits, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Traits, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Traits, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Actions, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Actions, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Actions, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Loot, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Loot, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Loot, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sense_Immunities, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Sense_Immunities, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sense_Immunities, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>